eexport function applyCombatOutcome(state: PlayerState, victory: boolean, enemyLevel: number): PlayerState {
  if (!victory) return state;
  const xpGain = 20 + Math.max(1, enemyLevel) * 10;
  const xp = state.xp + xpGain;
  const quests = state.quests.map(q => {
    if (q.id !== 'combat-1' || q.completed) return q;
    const progress = Math.min(q.target, q.progress + 1);
    return { ...q, progress, completed: progress >= q.target, rewardClaimed: q.rewardClaimed };
  });
  const completed = quests.find(q => q.id === 'combat-1' && q.completed && !q.rewardClaimed);
  return {
    ...state,
    xp,
    level: 1 + Math.floor(xp / 100),
    victories: state.victories + 1,
    worldThreat: Math.max(1, state.worldThreat - 1),
    worldResources: state.worldResources + 1 + (completed ? 3 : 0),
    quests: quests.map(q => q.id === 'combat-1' && completed ? { ...q, rewardClaimed: true } : q)
  };
}

export function grantArenaReward(state:PlayerState):PlayerState{const arenaWins=state.arenaWins+1,xp=state.xp+40+arenaWins*5,rarity:CardRarity=arenaWins%10===0?'Epic':arenaWins%3===0?'Rare':'Common',card:Card={id:`arena-${arenaWins}`,name:`Arena Reward #${arenaWins}`,...cardStats(arenaWins,rarity)};return{...state,arenaWins,victories:state.victories+1,xp,level:1+Math.floor(xp/100),cards:[...state.cards,card],fusionMaterials:state.fusionMaterials+1};}
const CARD_XP_PER_LEVEL=100;
export function upgradeCard(card:Card,xpGain:number):Card{const gain=Math.max(0,Math.floor(xpGain)),previousLevel=card.level,xp=Math.max(0,card.xp+gain),level=Math.max(1,1+Math.floor(xp/CARD_XP_PER_LEVEL)),levelsGained=Math.max(0,level-previousLevel);return{...card,xp,level,power:card.power+levelsGained*3,defense:card.defense+levelsGained*2,vitality:card.vitality+levelsGained*5};}
export function equipCard(state:PlayerState,cardId:string|null):PlayerState{if(cardId===null)return{...state,equippedCardId:null};return state.cards.some(c=>c.id===cardId)?{...state,equippedCardId:cardId}:state;}
export function getEquippedCard(state:PlayerState):Card|null{return state.cards.find(c=>c.id===state.equippedCardId)??null;}
const STORAGE_KEY='freedomarena:rpgqg:player:v1';
export function loadPlayer():PlayerState{try{const raw=localStorage.getItem(STORAGE_KEY);return raw?normalizePlayer(JSON.parse(raw) as Partial<PlayerState>):createStarterPlayer();}catch{return createStarterPlayer();}}
function normalizeCard(input:unknown):Card|null{if(!input||typeof input!=='object')return null;const c=input as Partial<Card>;if(typeof c.id!=='string'||typeof c.name!=='string')return null;const rarity:CardRarity=['Common','Rare','Epic','Legendary'].includes(c.rarity as string)?c.rarity as CardRarity:'Common';const n=(v:unknown,d:number)=>typeof v==='number'&&Number.isFinite(v)?Math.max(0,Math.floor(v)):d;return{id:c.id,name:c.name,rarity,power:n(c.power,0),defense:n(c.defense,0),vitality:Math.max(1,n(c.vitality,1)),xp:n(c.xp,0),level:Math.max(1,n(c.level,1))};}
export function normalizePlayer(input:Partial<PlayerState>):PlayerState{const s=createStarterPlayer(),cards=Array.isArray(input.cards)?input.cards.map(normalizeCard).filter((c):c is Card=>c!==null):[],equipped=typeof input.equippedCardId==='string'&&cards.some(c=>c.id===input.equippedCardId)?input.equippedCardId:null,fusionMaterials=typeof input.fusionMaterials==='number'&&Number.isFinite(input.fusionMaterials)?Math.max(0,Math.floor(input.fusionMaterials)):s.fusionMaterials,quests=Array.isArray(input.quests)?input.quests.filter(q=>q&&typeof q==='object').map(q=>{const quest=q as Quest,progress=Math.max(0,Math.floor(typeof quest.progress==='number'?quest.progress:0)),target=Math.max(1,Math.floor(typeof quest.target==='number'?quest.target:1));return{id:String(quest.id||''),title:String(quest.title||''),description:String(quest.description||''),progress:Math.min(progress,target),target,completed:Boolean(quest.completed)||progress>=target,rewardClaimed:Boolean(quest.rewardClaimed)};}):s.quests;return{...s,...input,name:typeof input.name==='string'&&input.name.trim()?input.name.trim().slice(0,24):s.name,level:typeof input.level==='number'&&Number.isFinite(input.level)?Math.max(1,Math.floor(input.level)):s.level,xp:typeof input.xp==='number'&&Number.isFinite(input.xp)?Math.max(0,Math.floor(input.xp)):s.xp,faction:factions.includes(input.faction as Faction)?input.faction as Faction:s.faction,victories:typeof input.victories==='number'&&Number.isFinite(input.victories)?Math.max(0,Math.floor(input.victories)):s.victories,cards,zoneId:typeof input.zoneId==='string'?input.zoneId:s.zoneId,explorationCount:typeof input.explorationCount==='number'&&Number.isFinite(input.explorationCount)?Math.max(0,Math.floor(input.explorationCount)):s.explorationCount,lastDiscovery:typeof input.lastDiscovery==='string'?input.lastDiscovery.slice(0,200):s.lastDiscovery,arenaWins:typeof input.arenaWins==='number'&&Number.isFinite(input.arenaWins)?Math.max(0,Math.floor(input.arenaWins)):s.arenaWins,equippedCardId:equipped,fusionMaterials,quests,worldThreat:typeof input.worldThreat==='number'&&Number.isFinite(input.worldThreat)?Math.max(1,Math.floor(input.worldThreat)):s.worldThreat,worldResources:typeof input.worldResources==='number'&&Number.isFinite(input.worldResources)?Math.max(0,Math.floor(input.worldResources)):s.worldResources,
    factionStates:Array.isArray(input.factionStates)?input.factionStates.filter(f=>f&&typeof f==='object').map(f=>{const x=f as WorldFactionState;return{faction:factions.includes(x.faction)?x.faction:'Aegis',influence:typeof x.influence==='number'?Math.max(0,Math.floor(x.influence)):100,reputation:typeof x.reputation==='number'?Math.floor(x.reputation):0};}):s.factionStates};}
export function validatePlayerState(state:PlayerState):string[]{const errors:string[]=[];if(!state.name.trim())errors.push('player name is empty');if(!Number.isInteger(state.level)||state.level<1)errors.push('player level is invalid');if(!Number.isInteger(state.xp)||state.xp<0)errors.push('player XP is invalid');if(!Number.isInteger(state.fusionMaterials)||state.fusionMaterials<0)errors.push('fusion materials are invalid');if(!Number.isInteger(state.worldThreat)||state.worldThreat<1)errors.push('world threat is invalid');if(!Number.isInteger(state.worldResources)||state.worldResources<0)errors.push('world resources are invalid');const ids=new Set<string>();for(const card of state.cards){if(ids.has(card.id))errors.push('duplicate card id: '+card.id);ids.add(card.id);if(!card.name.trim())errors.push('card name is empty: '+card.id);if(!['Common','Rare','Epic','Legendary'].includes(card.rarity))errors.push('invalid card rarity: '+card.id);if(!Number.isInteger(card.level)||card.level<1)errors.push('invalid card level: '+card.id);if(!Number.isInteger(card.xp)||card.xp<0)errors.push('invalid card XP: '+card.id);}if(state.equippedCardId!==null&&!ids.has(state.equippedCardId))errors.push('equipped card is missing');return errors;}
export function isValidPlayerState(state:PlayerState):boolean{return validatePlayerState(state).length===0;}
export function savePlayer(state:PlayerState):void{const normalized=normalizePlayer(state);if(!isValidPlayerState(normalized))return;localStorage.setItem(STORAGE_KEY,JSON.stringify(normalized));}
export function clearPlayerSave():void{localStorage.removeItem(STORAGE_KEY);}
const rarityOrder:CardRarity[]=['Common','Rare','Epic','Legendary'];
export function getNextRarity(rarity:CardRarity):CardRarity|null{const index=rarityOrder.indexOf(rarity);return index>=0&&index<rarityOrder.length-1?rarityOrder[index+1]:null;}
export function fuseCards(state:PlayerState,firstId:string,secondId:string):PlayerState{if(firstId===secondId)return state;const first=state.cards.find(c=>c.id===firstId),second=state.cards.find(c=>c.id===secondId);if(!first||!second||first.rarity!==second.rarity)return state;const rarity=getNextRarity(first.rarity),cost=getCardFusionCost(first.rarity);if(!rarity||state.fusionMaterials<cost)return state;const fused:Card={id:`fusion-${first.id}-${second.id}`,name:`${rarity} Fusion`,rarity,power:Math.round((first.power+second.power)/2)+2,defense:Math.round((first.defense+second.defense)/2)+1,vitality:Math.round((first.vitality+second.vitality)/2)+4,xp:Math.floor((first.xp+second.xp)/2),level:Math.max(first.level,second.level)},consumed=new Set([firstId,secondId]),cards=[...state.cards.filter(c=>!consumed.has(c.id)),fused];return{...state,cards,equippedCardId:consumed.has(state.equippedCardId??'')?fused.id:state.equippedCardId,fusionMaterials:state.fusionMaterials-cost};}
export function getCardFusionCost(rarity:CardRarity):number{return rarity==='Common'?2:rarity==='Rare'?4:rarity==='Epic'?8:Infinity;}
